// index.js - This is the logic file for the lab6 assignment
// Author: Carly Hunter
// Date: 11/05/24

// Constants

// Array to store custom texts entered by the user
let customTexts = [];
let customTextIndex = 0;

// Functions


// Example function and this comment tells what it does and what parameters are passed to it.
function myFunction(param1, param2) {
    // some code here
    // return results;
}

// Main function that initializes the app
function main() {
    console.log("Main function started.");
    // the code that makes everything happen

    // Initial random text displayed
    updateOutput(generateRandomText(), false);  // false indicates it's autogenerated
}

// Function to generate random Lorem Ipsum text
function generateRandomText() {
    const text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
    const min = 3;
    const max = 100;
    const randLen = Math.floor(Math.random() * (max - min + 1)) + min;
    
    // Get a random starting index to slice the Lorem Ipsum text
    const randStart = Math.floor(Math.random() * (text.length - randLen + 1));
    
    // Generate the random Lorem Ipsum-like text
    return text.slice(randStart, randStart + randLen);
}

// Function to append new text to the output div
function updateOutput(text, isUserGenerated) {
    // Add a class based on whether the text is user-generated
    const textClass = isUserGenerated ? 'user-text' : 'auto-text';
    $("#output").append('<div class="text ' + textClass + '"><p>' + text + '</p></div>');
}

// Click listener for button
$("#make-convo").click(function() {
    // Get the custom text from input field
    const customText = $("#custom-text").val().trim();
    
    // Add custom text to the array if it's provided
    if (customText) {
        customTexts.push(customText);
    }
    
    // Determine the next text to display
    let newText;
    let isUserGenerated;
    
    if (customTextIndex < customTexts.length) {
        newText = customTexts[customTextIndex];
        customTextIndex++;
        isUserGenerated = true;  // User-generated message
    } else {
        newText = generateRandomText();
        isUserGenerated = false;  // Auto-generated message
    }
    
    // Append the text to output div with appropriate styling
    updateOutput(newText, isUserGenerated);
    
    // Clear the input field for next entry
    $("#custom-text").val("");
});

// let's get this party started
main();
